import Head from "next/head";
import Image from "next/image";
import { Container, Paper, Navigation, Advertisment } from "../components";

export default function Home({ blogs }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="w-screen ">
        <Container>
          <div className="mt-[70px] grid gap-3 grid-cols-[240px_2fr_1fr] ">
            {/* Side bar  */}
            <div>
              <Paper>
                <div className="py-3 px-5">
                  <p className="text-[24px] font-medium mb-4 ">
                    Read Our Latest Blogs
                  </p>
                  <p className="text-[18px]">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                    Aliquam ut id malesuada pellentesque maecenas adipiscing
                    ante dis nunc. Faucibus sed lorem amet amet.
                  </p>
                </div>
              </Paper>
              <Navigation />
            </div>

            {/* Center content */}
            <main>
              {blogs.map((blog) => (
                <div key={blog.id} className="mb-3">
                  <Paper hover>
                    <div className="relative h-[230px] w-full">
                      <Image
                        src={blog.attributes.blog_img.data.attributes.url}
                        alt="hobbits house"
                        layout="fill"
                        objectFit="cover"
                        placeholder="blur"
                        blurDataURL="data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAADAAQDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAf/xAAbEAADAAMBAQAAAAAAAAAAAAABAgMABAURUf/EABUBAQEAAAAAAAAAAAAAAAAAAAMF/8QAFxEAAwEAAAAAAAAAAAAAAAAAAAECEf/aAAwDAQACEQMRAD8Anz9voy1dCI2mectSE5ioFCqia+KCwJ8HzGMZPqJb1oPEf//Z"
                      />
                    </div>
                    <div className="py-3 px-5">
                      <br />
                      <h2 className="text-[30px] font-bold ">
                        {blog.attributes.title}
                      </h2>
                      <p className="text-[14px] font-medium opacity-60 mb-7 ">
                        {/* Convert date in static props */}
                        {new Date(blog.attributes.publishedAt).toDateString()}
                      </p>
                      <p className="text-[18px]  ">
                        {blog.attributes.body.substring(1, 250)}...
                      </p>
                    </div>
                  </Paper>
                </div>
              ))}
            </main>

            {/* Right sidebar */}
            <Advertisment />
          </div>
        </Container>
      </div>
    </div>
  );
}

export async function getStaticProps() {
  try {
    const res = await fetch(
      "http://localhost:1337/api/blogs?populate=blog_img"
    );
    const { data: blogs } = await res.json();

    return { props: { blogs } };
  } catch (e) {
    console.warn(e.message);
    return { props: {} };
  }
}
